site_name: Laz
site_url: https://joshwycuff.github.io/py-laz
theme:
  name: material
nav:
  - index.md
  - quick_start.md
  - concepts.md
  - configuration.md
  - actions.md
  - plugins.md
  - cli.md
